imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1.0.1
        assets_version_format: '%%s?v=%%s'
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: secured_area
    user_class: AppBundle\Entity\User
    from_email:
        address: "info@quot.com"
        sender_name: "info quot"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles:
         - AppBundle
         - HWIOAuthBundle
         - FOSUserBundle
    assets:
      gotham-book-otf:
        inputs: '%kernel.root_dir%/Resources/public/fonts/GOTHAM-BOOK.OTF'
        output: 'fonts/gotham-book.otf'
      gotham-medium-otf:
        inputs: '%kernel.root_dir%/Resources/public/fonts/GOTHAM-MEDIUM.OTF'
        output: 'fonts/gotham-medium.otf'
      questa-grande-otf:
        inputs: '%kernel.root_dir%/Resources/public/fonts/2-questa_grande_regular_31.otf'
        output: 'fonts/questa-grande.otf'
      glyphicons-halflings-eot:
        inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.eot'
        output: 'fonts/glyphicons-halflings-regular.eot'
      glyphicons-halflings-ttf:
        inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.ttf'
        output: 'fonts/glyphicons-halflings-regular.ttf'
      glyphicons-halflings-svg:
        inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.svg'
        output: 'fonts/glyphicons-halflings-regular.svg'
      glyphicons-halflings-woff:
        inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.woff'
        output: 'fonts/glyphicons-halflings-regular.woff'
      glyphicons-halflings-woff2:
        inputs: '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.woff2'
        output: 'fonts/glyphicons-halflings-regular.woff2'
    filters:
        cssrewrite: ~
