parameters:
    database_host: b4e9xxkxnpu2v96i.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
    database_port: 3306
    database_name: y9wzkem4bhhq8xxf
    database_user: tbg87rs1brbjt076
    database_password: h9cnu60re0zypq7w
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
    json_productos: http://quotstore.com:8888/productos
    json_home: http://quotstore.com:8888/modulos-home
    access_codes: [UQ6VCX, UQY5ZS, UQQ24X, UQM8E5,UQ2SUX, UQ6TZG, UQZBF2, UQTWVH, UQB5GT, UQ99TX, UQAYH8, UQVYZV, UQUHRN, UQN5XH, UQTPN4, UQGZLW, UQ46VP, UQ94K9, UQW5HN, UQYGPG, UQVHW7, UQ4LGK, UQA5Q2, UQ95MP, UQWF2A, UQTWUJ, UQGYYR, UQV63P, UQS8L7, UQJZXV, UQFTWK, UQP53D, UQH9XB, UQXG5U, UQ5XW3, UQ8HU8, UQ3JX3, UQMWBT, UQJ48C, UQ4PBE, UQWT4L, UQY6PX, UQKJJJ, UQZ499, UQCBD4, UQ5JBK, UQW3BY, UQVVUR, UQ78VD, UQRBW2, UQ7WEH, UQRQ2E, UQPRPN, UQXVUY, UQCE9W, UQMM7G, UQXQZG, UQ6US5, UQY4PV, UQTUJ5, UQDZW6, UQSJAJ, UQWR7Y, UQB8G2, UQBEPC, UQSC4Q, UQ4YHZ, UQSTDR, UQGU46, UQZQL4, UQKCBN, UQHEW8, UQY72R, UQTA7T, UQUKKN, UQ7TXR, UQUNQU, UQEWRG, UQMPTM, UQ2EFX]
    reference_payment: compra_quot_
    reference_payment_subscription: compra_suscripcion_
    url_payU: https://gateway.payulatam.com/ppp-web-gateway
    merchatId: 630936
    accountId: 633275
    apiKey: FhkmbRHL3nAveKjQ1IKEr6Qh8i
    iva: 0.19
    total_subscription: 70000
    test_payU: 0
