#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

home:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
product_list:
    path:     /demo/product-list
    defaults: { _controller: AppBundle:Home:list }
