#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

home:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
product_list:
    path:     /demo/product-list
    defaults: { _controller: AppBundle:Home:list }
product_modal:
    path:     /demo/product-list-modal
    defaults: { _controller: AppBundle:Home:modal }
product_to_cart:
    path:     /demo/product-to-cart
    defaults: { _controller: AppBundle:Home:productToCart }
