#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

home:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
product_list:
    path:     /demo/product-list
    defaults: { _controller: AppBundle:Home:list }
product_modal:
    path:     /demo/product-list-modal
    defaults: { _controller: AppBundle:Home:modal }
product_to_cart:
    path:     /demo/product-to-cart
    defaults: { _controller: AppBundle:Home:productToCart }
login:
    path:     /demo/login
    defaults: { _controller: AppBundle:Home:login }
sign-up-one:
    path:     /demo/sign-up-one
    defaults: { _controller: AppBundle:Home:signUpOne }
sign-up-two:
    path:     /demo/sign-up-two
    defaults: { _controller: AppBundle:Home:signUpTwo }
payment-method:
    path:     /demo/payment-method
    defaults: { _controller: AppBundle:Home:paymentMethod }
cart-items:
    path:     /demo/cart-items
    defaults: { _controller: AppBundle:Home:cartItems }
