#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

home:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
product_list:
    path:     /demo/product-list
    defaults: { _controller: AppBundle:Home:list }
product_modal:
    path:     /demo/product-list-modal
    defaults: { _controller: AppBundle:Home:modal }
product_to_cart:
    path:     /demo/product-to-cart
    defaults: { _controller: AppBundle:Home:productToCart }
login:
    path:     /demo/login
    defaults: { _controller: AppBundle:Home:login }
sign-up-one:
    path:     /demo/sign-up-one
    defaults: { _controller: AppBundle:Home:signUpOne }
sign-up-two:
    path:     /demo/sign-up-two
    defaults: { _controller: AppBundle:Home:signUpTwo }
payment-method:
    path:     /demo/payment-method
    defaults: { _controller: AppBundle:Home:paymentMethod }
cart-items:
    path:     /demo/cart-items
    defaults: { _controller: AppBundle:Home:cartItems }
product-customization:
    path:     /demo/product-customization
    defaults: { _controller: AppBundle:Home:productCustomization }
products:
    path:     /colecciones
    defaults: { _controller: AppBundle:Products:collections }
custom:
    path:     /personalizar/{vidParent}/{vid}/{size}
    defaults: { _controller: AppBundle:Products:custom }
custom-detail:
    path:     /personalizar/detalle
    defaults: { _controller: AppBundle:Products:customDetail }
data-product:
    path:     /data-product
    defaults: { _controller: AppBundle:Products:dataProduct }
save-purchase:
    path:     /save-purchase
    defaults: { _controller: AppBundle:Services:savePurchase }    
save-preorder:
    path:     /save-preorder
    defaults: { _controller: AppBundle:Services:savePreOrder }
list-products-orders:
    path:     /resumen-compra
    defaults: { _controller: AppBundle:Services:listProductsOrder }
