#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

home:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
new_home:
    path: /new_home
    defaults: { _controller: AppBundle:Home:newHome }
product_list:
    path:     /demo/product-list
    defaults: { _controller: AppBundle:Home:list }
product_modal:
    path:     /demo/product-list-modal
    defaults: { _controller: AppBundle:Home:modal }
product_to_cart:
    path:     /demo/product-to-cart
    defaults: { _controller: AppBundle:Home:productToCart }
login:
    path:     /demo/login
    defaults: { _controller: AppBundle:Home:login }
sign-up-one:
    path:     /demo/sign-up-one
    defaults: { _controller: AppBundle:Home:signUpOne }
sign-up-two:
    path:     /demo/sign-up-two
    defaults: { _controller: AppBundle:Home:signUpTwo }
payment-method:
    path:     /demo/payment-method
    defaults: { _controller: AppBundle:Home:paymentMethod }
cart-items:
    path:     /demo/cart-items
    defaults: { _controller: AppBundle:Home:cartItems }
product-customization:
    path:     /demo/product-customization
    defaults: { _controller: AppBundle:Home:productCustomization }
product-resume:
    path:     /demo/product-resume
    defaults: { _controller: AppBundle:Home:productResume }
products:
    path:     /colecciones
    defaults: { _controller: AppBundle:Products:collections }
custom:
    path:     /personalizar/{vidParent}/{vid}/{size}
    defaults: { _controller: AppBundle:Products:custom }
custom-detail:
    path:     /personalizar/detalle
    defaults: { _controller: AppBundle:Products:customDetail }
custom-detail-ajax:
    path:     /personalizar/detalle-ajax
    defaults: { _controller: AppBundle:Products:customDetailAjax }
data-product:
    path:     /data-product
    defaults: { _controller: AppBundle:Products:dataProduct }
save-purchase:
    path:     /save-purchase
    defaults: { _controller: AppBundle:Services:savePurchase }
save-preorder:
    path:     /save-preorder
    defaults: { _controller: AppBundle:Services:savePreOrder }
list-products-orders:
    path:     /resumen-compra
    defaults: { _controller: AppBundle:Services:listProductsOrder }
completed-shirt:
    path:     /resumen-camisa
    defaults: { _controller: AppBundle:Products:completedShirt }
purchase:
    path:     /comprar
    defaults: { _controller: AppBundle:Services:purchase }
newsletter:
    path:     /newsletter-send
    defaults: { _controller: AppBundle:Services:newsletter }
address:
    path:     /direccion-envio
    defaults: { _controller: AppBundle:User:address }
address_save:
    path:     /save-address
    defaults: { _controller: AppBundle:Services:saveAddress }
result_compra:
    path:     /resultado-compra
    defaults: { _controller: AppBundle:Services:resultCompra }
module_trans:
    path:     /module-trans
    defaults: { _controller: AppBundle:Products:moduleTrans }
count_shirt:
    path:     /count-shirt
    defaults: { _controller: AppBundle:Services:countShirt }
cart-purchase:
    path:     /carro-compras
    defaults: { _controller: AppBundle:Services:cartPurchase }
